/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsQrCodeGeneratorRouteImport } from './routes/tools/qr-code-generator'
import { Route as ToolsPdfToJpgRouteImport } from './routes/tools/pdf-to-jpg'
import { Route as ToolsPassportPhotoRouteImport } from './routes/tools/passport-photo'
import { Route as ToolsInvoiceGeneratorRouteImport } from './routes/tools/invoice-generator'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools/image-compressor'
import { Route as ToolsCurrencyConverterRouteImport } from './routes/tools/currency-converter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrCodeGeneratorRoute = ToolsQrCodeGeneratorRouteImport.update({
  id: '/tools/qr-code-generator',
  path: '/tools/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToJpgRoute = ToolsPdfToJpgRouteImport.update({
  id: '/tools/pdf-to-jpg',
  path: '/tools/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPassportPhotoRoute = ToolsPassportPhotoRouteImport.update({
  id: '/tools/passport-photo',
  path: '/tools/passport-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsInvoiceGeneratorRoute = ToolsInvoiceGeneratorRouteImport.update({
  id: '/tools/invoice-generator',
  path: '/tools/invoice-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCurrencyConverterRoute = ToolsCurrencyConverterRouteImport.update({
  id: '/tools/currency-converter',
  path: '/tools/currency-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/invoice-generator': typeof ToolsInvoiceGeneratorRoute
  '/tools/passport-photo': typeof ToolsPassportPhotoRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/invoice-generator': typeof ToolsInvoiceGeneratorRoute
  '/tools/passport-photo': typeof ToolsPassportPhotoRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/invoice-generator': typeof ToolsInvoiceGeneratorRoute
  '/tools/passport-photo': typeof ToolsPassportPhotoRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/tools/currency-converter'
    | '/tools/image-compressor'
    | '/tools/invoice-generator'
    | '/tools/passport-photo'
    | '/tools/pdf-to-jpg'
    | '/tools/qr-code-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/tools/currency-converter'
    | '/tools/image-compressor'
    | '/tools/invoice-generator'
    | '/tools/passport-photo'
    | '/tools/pdf-to-jpg'
    | '/tools/qr-code-generator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/tools/currency-converter'
    | '/tools/image-compressor'
    | '/tools/invoice-generator'
    | '/tools/passport-photo'
    | '/tools/pdf-to-jpg'
    | '/tools/qr-code-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsCurrencyConverterRoute: typeof ToolsCurrencyConverterRoute
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsInvoiceGeneratorRoute: typeof ToolsInvoiceGeneratorRoute
  ToolsPassportPhotoRoute: typeof ToolsPassportPhotoRoute
  ToolsPdfToJpgRoute: typeof ToolsPdfToJpgRoute
  ToolsQrCodeGeneratorRoute: typeof ToolsQrCodeGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-code-generator': {
      id: '/tools/qr-code-generator'
      path: '/tools/qr-code-generator'
      fullPath: '/tools/qr-code-generator'
      preLoaderRoute: typeof ToolsQrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-jpg': {
      id: '/tools/pdf-to-jpg'
      path: '/tools/pdf-to-jpg'
      fullPath: '/tools/pdf-to-jpg'
      preLoaderRoute: typeof ToolsPdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/passport-photo': {
      id: '/tools/passport-photo'
      path: '/tools/passport-photo'
      fullPath: '/tools/passport-photo'
      preLoaderRoute: typeof ToolsPassportPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/invoice-generator': {
      id: '/tools/invoice-generator'
      path: '/tools/invoice-generator'
      fullPath: '/tools/invoice-generator'
      preLoaderRoute: typeof ToolsInvoiceGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/currency-converter': {
      id: '/tools/currency-converter'
      path: '/tools/currency-converter'
      fullPath: '/tools/currency-converter'
      preLoaderRoute: typeof ToolsCurrencyConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsCurrencyConverterRoute: ToolsCurrencyConverterRoute,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsInvoiceGeneratorRoute: ToolsInvoiceGeneratorRoute,
  ToolsPassportPhotoRoute: ToolsPassportPhotoRoute,
  ToolsPdfToJpgRoute: ToolsPdfToJpgRoute,
  ToolsQrCodeGeneratorRoute: ToolsQrCodeGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
